### ISSUE TITLE
Support of Node.js 9

### ISSUE THREAD

**Issue by rkosenko** [michaelwayman/node-sass-chokidar#29]
`node-sass-chokidar` doesn't work with the last Nove version:
```
$ node --version
v9.2.0
$ yarn start
yarn run v1.3.2
$ npm-run-all -p watch-css start-js
$ react-app-rewired start
$ yarn run build-css && node-sass-chokidar src/ -o src/ --watch --recursive
$ node-sass-chokidar src/ -o src/
/home/rkosenko/src/Sagax/pips/frontend/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/rkosenko/src/Sagax/pips/frontend/node_modules/node-sass/vendor/linux-x64-59/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 9.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/home/rkosenko/src/Sagax/pips/frontend/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/rkosenko/src/Sagax/pips/frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rkosenko/src/Sagax/pips/frontend/node_modules/node-sass-chokidar/bin/node-sass-chokidar:18:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "watch-css" exited with 1.
error Command failed with exit code 1.
```
It will be nice to have it.

**Comment by ValeryIvanov** [comment]
I think you just need to run npm install. Probably you changed node version and packages need to be reinstalled after that.

**Comment by will-stone** [comment]
I had this same issue: deleting node_modules and re-running yarn fixed the problem.

**Comment by michaelwayman** [comment]
Sorry for taking so long getting back, but I tested this on node v9.2 and it appears to be working.
Feel free to reopen the issue if you are still having problems, but it seems like you might need to try uninstalling your node_modules and reinstalling.
