### ISSUE TITLE
No longer compiling after updating react-scripts from 1.0.10 to 1.0.17

### ISSUE THREAD

**Issue by nickfday** [michaelwayman/node-sass-chokidar#30]
I am now getting the follow error after updating react-scripts to 1.0.17. Before it was successfully compiling scss to css after running npm start. Still watches but no longer compiles after scss changes.

"start": "npm run watch-css | react-scripts start",

After running 'npm start'

^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! wcc-calendar-app@0.1.0 start: `npm run watch-css | react-scripts start`
npm ERR! Exit status 130
npm ERR!
npm ERR! Failed at the wcc-calendar-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nickf/.npm/_logs/2017-12-06T12_20_08_077Z-debug.log
---------------------------------------------------------------------------------------------
/Users/nickf/.npm/_logs/2017-12-06T12_20_08_077Z-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wcc-calendar-app@0.1.0~prestart: wcc-calendar-app@0.1.0
6 info lifecycle wcc-calendar-app@0.1.0~start: wcc-calendar-app@0.1.0
7 verbose lifecycle wcc-calendar-app@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle wcc-calendar-app@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/nickf/www-2017/wcc-calendar-app-bitbucket/node_modules/.bin:/Users/nickf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nickf/.rvm/bin
9 verbose lifecycle wcc-calendar-app@0.1.0~start: CWD: /Users/nickf/www-2017/wcc-calendar-app-bitbucket
10 silly lifecycle wcc-calendar-app@0.1.0~start: Args: [ '-c', 'npm run watch-css | react-scripts start' ]
11 silly lifecycle wcc-calendar-app@0.1.0~start: Returned: code: 130  signal: null
12 info lifecycle wcc-calendar-app@0.1.0~start: Failed to exec start script
13 verbose stack Error: wcc-calendar-app@0.1.0 start: `npm run watch-css | react-scripts start`
13 verbose stack Exit status 130
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wcc-calendar-app@0.1.0
15 verbose cwd /Users/nickf/www-2017/wcc-calendar-app-bitbucket
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 130
22 error wcc-calendar-app@0.1.0 start: `npm run watch-css | react-scripts start`
22 error Exit status 130
23 error Failed at the wcc-calendar-app@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 130, true ]

**Comment by nickfday** [comment]
Running the following command fixed the problem:
'npm rebuild node-sass --force'

**Comment by nickfday** [comment]
Closing issue.
