### ISSUE TITLE
Source map option breaks the build

### ISSUE THREAD

**Issue by Pixelatex** [michaelwayman/node-sass-chokidar#70]
This is my command:

`    "sass:build": "node-sass-chokidar src/style/scss -o src/style/css --source-map",
`

The error it outputs:

```
var sourceMapIsDirectory = options.sourceMapOriginal.indexOf('.map', options.sourceMapOriginal.length - 4) === -1 && isDirectory(options.sourceMapOriginal);
                                                         ^

TypeError: options.sourceMapOriginal.indexOf is not a function
    at getOptions (/Users/xx/Repositories/sb-admin-panel-2.0/node_modules/node-sass-chokidar/bin/node-sass-chokidar:207:58)
    at Object.<anonymous> (/Users/xx/Repositories/sb-admin-panel-2.0/node_modules/node-sass-chokidar/bin/node-sass-chokidar:439:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

Anyone who can help me with this?

**Comment by emoffett** [comment]
`"... --source-map true"` help?
